spring:
  application:
    name: login
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  secret: your-very-long-secret-key-string-at-least-32-characters
  access-expire-millis: 1800000  # 액세스 토큰 만료: 30분
  refresh-expire-millis: 864000000 # 리프레시 토큰 만료: 10일